### ISSUE TITLE
Library incompatible with Python 3.12

### ISSUE THREAD

**Issue by rootabeta** [audreyreal/NSDotPy#13]
With the release of Python 3.12 this past month, I noticed that one of my own projects that relies on nsdotpy fails to acquire nsdotpy on Python 3.12. Subsequent investigation revealed that nsdotpy is packaged such that it advertises itself as incompatible with versions higher than 3.11. This breaks any python program attempting to use nsdotpy on Python 3.12+

**Comment by audreyreal** [comment]
fixed
